{
  "openapi": "3.0.1",
  "info": {
    "version": "0.1.15",
    "title": "Swagger for pets",
    "description": "Showing off swagger-ui-express",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [
    { "url": "https://pet-web-server.onrender.com" },
    { "url": "http://localhost:3030/" }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "User",
      "description": "User endpoints"
    },
    {
      "name": "Other",
      "description": "Public routes like news and sponsors"
    },
    {
      "name": "Notices",
      "description": "Public routes with notices and info about sell, find, and so on"
    }
  ],
  "paths": {
    "/api/auth/registration": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          }
        }
      }
    },
    "/api/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "parameters": [],
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "No Authorization",
            "content": {}
          }
        }
      }
    },
    "/api/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "id object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/logoutRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful logout",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/logoutResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request ",
            "content": {}
          }
        }
      }
    },
    "/api/auth/verify/:verificationToken": {
      "get": {
        "tags": ["Auth"],
        "summary": "Verification User",
        "parameters": [
          {
            "in": "path",
            "name": "verificationToken",
            "required": true,
            "type": "string",
            "description": "verificationToken User's"
          }
        ],

        "responses": {
          "200": {
            "description": "Email verify success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/verifyResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email not found ",
            "content": {}
          }
        }
      }
    },
    "/api/auth/verify": {
      "post": {
        "tags": ["Auth"],
        "summary": "resend verify email user",
        "parameters": [],

        "requestBody": {
          "description": "id object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/resendVerifyRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Verify email send success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/resendVerifyResponse"
                }
              }
            }
          },
          "400": {
            "description": "Email not found ",
            "content": {}
          },
          "401": {
            "description": "Email already verify ",
            "content": {}
          }
        }
      }
    },
    "/api/user/pets": {
      "get": {
        "tags": ["User"],
        "summary": "List your pets",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful list pets",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/listPetResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request ",
            "content": {}
          }
        }
      },
      "post": {
        "tags": ["User"],
        "summary": "Add your pet",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "pet object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/addPetRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful added pet",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/addPetResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request ",
            "content": {}
          }
        }
      }
    },
    "api/user/pets/:id": {
      "put": {
        "tags": ["User"],
        "summary": "update info about my pet",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string",
            "description": "Pet's id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "pet object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/updateInfoPetRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful update info operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/updateInfoPetResponses"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      },
      "delete": {
        "tags": ["User"],
        "summary": "delete pet by id",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string",
            "description": "Pet's id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Successful delete ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/deletePetResponses"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid id)",
            "content": {}
          }
        }
      }
    },
    "api/user/current": {
      "get": {
        "tags": ["User"],
        "summary": "Get info current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/infoCurrentUserResponses"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      },
      "put": {
        "tags": ["User"],
        "summary": "Update info current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "user object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/updateInfoUserRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful update info ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/updateInfoUserResponses"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "api/user/avatar": {
      "patch": {
        "tags": ["User"],
        "summary": "Update avatar user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/news?offset=3&limit=25": {
      "get": {
        "tags": ["Other"],
        "summary": "Return list of news about pets",
        "parameters": [
          {
            "in": "query",
            "name": "offset",
            "schema": {
              "type": "integer"
            },
            "description": "The page number",
            "requred": false,
            "type": "number",
            "example": 5,
            "default": 1
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer"
            },
            "description": "The number of items",
            "requred": false,
            "type": "number",
            "example": 20,
            "default": 10
          }
        ],
        "responses": {
          "200": {
            "description": "Successful fetch news",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/newsResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/notices": {
      "get": {
        "tags": ["Notices"],
        "summary": "Get all notices"
      },
      "post": {
        "tags": ["Notices"],
        "summary": "add new notice"
      }
    },
    "/api/notices/{noticeId}": {
      "get": {
        "tags": ["Notices"],
        "summary": "Get info about one notice"
      },
      "delete": {
        "tags": ["Notices"],
        "summary": "Get info about one notice"
      }
    },
    "/api/notices/{noticeId}/addToFavorite": {
      "patch": {
        "tags": ["Notices"],
        "summary": "Add notice to Favorite"
      }
    },
    "/api/notices/{noticeId}/removeFromFavorite": {
      "patch": {
        "tags": ["Notices"],
        "summary": "Remove notice to Favorite"
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "format": "email",
            "example": "Godrik"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "godrik999@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "User's id"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          }
        },
        "example": [
          {
            "email": "godrik999@gmail.com",
            "id": "8976asdf897asd02798hc73jnh"
          }
        ]
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "godrik999@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "User's id"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          }
        },
        "example": [
          {
            "email": "godrik999@gmail.com",
            "id": "8976asdf897asd02798hc73jnh"
          }
        ]
      },
      "verifyResponse": {
        "type": "object",
        "properties": {},
        "example": {
          "message": "Email verify success"
        }
      },
      "resendVerifyRequest": {
        "type": "object",
        "required": ["email"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "godrik999@gmail.com"
          }
        }
      },
      "resendVerifyResponse": {
        "type": "object",
        "properties": {},
        "example": {
          "message": "Verify email send success"
        }
      },
      "addPetRequest": {
        "type": "object",
        "required": [
          "name",
          "birthday",
          "type",
          "comments",
          "location",
          "price",
          "filter"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "Pet's name",
            "format": "name",
            "example": "Barsik"
          },
          "birthday": {
            "type": "number",
            "description": "Pet's birthday",
            "format": "number",
            "example": "11.12.2020"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Sheepdog"
          },
          "comments": {
            "type": "string",
            "description": "Comments about your pet ",
            "example": "Jack is a handsome Basenji with short, shiny red fur and perky ears. He's an active and intelligent dog that loves to explore and play. Jack is independent and strong-willed, but also affectionate and loyal to his family. He's a curious and energetic companion that brings joy and adventure to his family's life."
          },
          "location": {
            "type": "string",
            "description": "Pet's location",
            "format": "string",
            "example": "Lviv"
          },
          "price": {
            "type": "number",
            "description": "Pet's price",
            "format": "number",
            "example": 21312
          },
          "filter": {
            "type": "string",
            "description": "sell, lost/found, in good hands, found",
            "format": "string",
            "example": "sell"
          }
        }
      },
      "addPetResponse": {
        "type": "object",
        "required": ["name", "birthday", "type", "comments"],
        "properties": {
          "id": {
            "type": "string",
            "description": "Pet's name",
            "format": "string",
            "example": "kujnsd87hsd9232n3d3d2"
          },
          "name": {
            "type": "string",
            "description": "Pet's name",
            "format": "name",
            "example": "Barsik"
          },
          "birthday": {
            "type": "number",
            "description": "Pet's birthday",
            "format": "number",
            "example": "11.12.2020"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Sheepdog"
          },
          "comments": {
            "type": "string",
            "description": "Comments about your pet ",
            "example": "Jack is a handsome Basenji with short, shiny red fur and perky ears. He's an active and intelligent dog that loves to explore and play. Jack is independent and strong-willed, but also affectionate and loyal to his family. He's a curious and energetic companion that brings joy and adventure to his family's life."
          }
        }
      },
      "listPetResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Pet's name",
              "format": "name",
              "example": "Barsik"
            },
            "birthday": {
              "type": "number",
              "description": "Pet's birthday",
              "format": "number",
              "example": "11.12.2020"
            },
            "type": {
              "type": "string",
              "description": "Pet's type",
              "example": "Sheepdog"
            },
            "comments": {
              "type": "string",
              "description": "Comments about your pet ",
              "example": "Jack is a handsome Basenji with short, shiny red fur and perky ears. He's an active and intelligent dog that loves to explore and play. Jack is independent and strong-willed, but also affectionate and loyal to his family. He's a curious and energetic companion that brings joy and adventure to his family's life."
            }
          }
        },
        "example": [
          {
            "id": "8976asdf897asd02798hc73jnh",
            "name": "Jack",
            "birthday": "03.04.2021",
            "type": "Persian cat",
            "comments": " Jack is a gray Persian cat with green eyes. He loves to be pampered and groomed, and enjoys playing with toys. Although a bit shy, he's a loyal and affectionate lap cat."
          },
          {
            "id": "0909kwe0-v9k23pioklimvadsfa",
            "name": "Barsik",
            "birthday": "11.12.2020",
            "type": "Sheepdog",
            "comments": " Barsik is a handsome Basenji with short, shiny red fur and perky ears. He's an active and intelligent dog that loves to explore and play"
          }
        ]
      },
      "updateInfoPetRequest": {
        "type": "object",
        "required": ["name", "birthday", "type", "comments"],
        "properties": {
          "name": {
            "type": "string",
            "description": "Pet's name",
            "format": "name",
            "example": "Barsik"
          },
          "birthday": {
            "type": "number",
            "description": "Pet's birthday",
            "format": "number",
            "example": "11.12.2020"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Sheepdog"
          },
          "comments": {
            "type": "string",
            "description": "Comments about your pet ",
            "example": "Jack is a handsome Basenji with short, shiny red fur and perky ears. He's an active and intelligent dog that loves to explore and play. Jack is independent and strong-willed, but also affectionate and loyal to his family. He's a curious and energetic companion that brings joy and adventure to his family's life."
          }
        }
      },
      "updateInfoPetResponses": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Pet's id",
            "format": "string",
            "example": "907d8sayhiashdbciuasdvc9786g3c"
          },
          "name": {
            "type": "string",
            "description": "Pet's name",
            "format": "name",
            "example": "Barsik"
          },
          "birthday": {
            "type": "number",
            "description": "Pet's birthday",
            "format": "number",
            "example": "11.12.2020"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Sheepdog"
          },
          "comments": {
            "type": "string",
            "description": "Comments about your pet ",
            "example": "Jack is a handsome Basenji with short, shiny red fur and perky ears. He's an active and intelligent dog that loves to explore and play. Jack is independent and strong-willed, but also affectionate and loyal to his family. He's a curious and energetic companion that brings joy and adventure to his family's life."
          }
        }
      },

      "deletePetResponses": {
        "type": "object",
        "properties": {},
        "example": {
          "message": "Pet with {id} delete success"
        }
      },
      "logoutRequest": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "User's id"
          }
        },
        "example": {
          "id": "8976asdf897asd02798hc73jnh"
        }
      },
      "logoutResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "message"
          }
        },
        "example": {
          "message": "you have exited successfully"
        }
      },
      "listAllPets": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "id",
              "format": "name",
              "example": "rtfg4343t434g334ggg34a43"
            },
            "name": {
              "type": "string",
              "description": "Pet's name",
              "format": "name",
              "example": "Barsik"
            },
            "birthday": {
              "type": "number",
              "description": "Pet's birthday",
              "format": "number",
              "example": "11.12.2020"
            },
            "type": {
              "type": "string",
              "description": "Pet's type",
              "example": "Sheepdog"
            },
            "comments": {
              "type": "string",
              "description": "Comments about your pet ",
              "example": "Jack is a handsome Basenji with short, shiny red fur and perky ears. He's an active and intelligent dog that loves to explore and play. Jack is independent and strong-willed, but also affectionate and loyal to his family. He's a curious and energetic companion that brings joy and adventure to his family's life."
            }
          }
        },
        "example": [
          {
            "id": "8976asdf897asd02798hc73jnh",
            "name": "Jack",
            "birthday": "03.04.2021",
            "type": "Persian cat",
            "comments": " Jack is a gray Persian cat with green eyes. He loves to be pampered and groomed, and enjoys playing with toys. Although a bit shy, he's a loyal and affectionate lap cat."
          },
          {
            "id": "0909kwe0-v9k23pioklimvadsfa",
            "name": "Barsik",
            "birthday": "11.12.2020",
            "type": "Sheepdog",
            "comments": " Barsik is a handsome Basenji with short, shiny red fur and perky ears. He's an active and intelligent dog that loves to explore and play"
          }
        ]
      },
      "infoCurrentUserResponses": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "id",
            "format": "string",
            "example": "rtfg4343t434g334ggg34a43"
          },
          "name": {
            "type": "string",
            "description": "User name",
            "format": "name",
            "example": "Godrik"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email",
            "example": "godrik999@gmail.com"
          },
          "birthday": {
            "type": "number",
            "description": "User's birthday",
            "format": "number",
            "example": "11.12.2020"
          },
          "phone": {
            "type": "number",
            "description": "User's phone",
            "format": "number",
            "example": 9876543212
          },
          "city": {
            "type": "string",
            "description": "User's city",
            "format": "string",
            "example": "Lviv"
          }
        },
        "example": {
          "id": "0909kwe0-v9k23pioklimvadsfa",
          "name": "Godrik",
          "email": "godrik999@gmail.com",
          "birthday": "11.12.2020",
          "phone": 9876543212,
          "city": "Lviv"
        }
      },
      "updateInfoUserRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User name",
            "format": "name",
            "example": "Godrik"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email",
            "example": "godrik999@gmail.com"
          },
          "birthday": {
            "type": "number",
            "description": "User's birthday",
            "format": "number",
            "example": "11.12.2020"
          },
          "phone": {
            "type": "number",
            "description": "User's phone",
            "format": "number",
            "example": 9876543212
          },
          "city": {
            "type": "string",
            "description": "User's city",
            "format": "string",
            "example": "Lviv"
          }
        },
        "example": {
          "name": "Godrik",
          "email": "godrik999@gmail.com",
          "birthday": "11.12.2020",
          "phone": 9876543212,
          "city": "Lviv"
        }
      },
      "updateInfoUserResponses": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User name",
            "format": "name",
            "example": "Godrik"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email",
            "example": "godrik999@gmail.com"
          },
          "birthday": {
            "type": "number",
            "description": "User's birthday",
            "format": "number",
            "example": "11.12.2020"
          },
          "phone": {
            "type": "number",
            "description": "User's phone",
            "format": "number",
            "example": 9876543212
          },
          "city": {
            "type": "string",
            "description": "User's city",
            "format": "string",
            "example": "Lviv"
          }
        },
        "example": {
          "id": "0909kwe0-v9k23pioklimvadsfa",
          "name": "Godrik",
          "email": "godrik999@gmail.com",
          "birthday": "11.12.2020",
          "phone": 9876543212,
          "city": "Lviv"
        }
      },
      "newsResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "Status query",
            "format": "string",
            "example": "ok"
          },
          "code": {
            "type": "number",
            "description": "duplicate response code",
            "format": "number",
            "example": 200
          },
          "data": {
            "type": "object",
            "properties": {
              "resourses": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string",
                      "description": "news id",
                      "format": "name",
                      "example": "655a08473e09b17fe5eeed27"
                    },
                    "imgUrl": {
                      "type": "string",
                      "description": "Pet's name",
                      "format": "name",
                      "example": "Barsik"
                    },
                    "title": {
                      "type": "string",
                      "description": "Pet's name",
                      "format": "name",
                      "example": "Barsik"
                    },
                    "text": {
                      "type": "string",
                      "description": "Pet's name",
                      "format": "name",
                      "example": "Barsik"
                    },
                    "date": {
                      "type": "string",
                      "description": "Pet's name",
                      "format": "name",
                      "example": "Barsik"
                    },
                    "url": {
                      "type": "string",
                      "description": "Pet's name",
                      "format": "name",
                      "example": "Barsik"
                    },
                    "nytID": {
                      "type": "string",
                      "description": "Pet's name",
                      "format": "name",
                      "example": "Barsik"
                    }
                  }
                }
              },
              "total": {
                "type": "number",
                "example": 123
              },
              "totalPages": {
                "type": "number",
                "example": 23213
              }
            }
          }
        },
        "example": {
          "status": "ok",
          "code": 200,
          "data": {
            "resourses": [
              {
                "_id": "655a08473e09b17fe5eeed27",
                "imgUrl": "https://www.nytimes.com/images/2023/04/16/magazine/16mag-LOR/16mag-LOR-blog480.jpg",
                "title": "What I Learned Dogsitting for New York City’s Opulent Elite",
                "text": "In a city of yawning class inequality, some side hustles let you glimpse how the other half lives.",
                "date": "2023-04-11T09:00:18.000Z",
                "url": "https://www.nytimes.com/2023/04/11/magazine/dogsitting-rich-new-york.html",
                "nytID": "nyt://article/8d29f1fc-d146-509d-8ceb-5a5b17d7886b",
                "createdAt": "2023-11-19T13:06:16.190Z",
                "updatedAt": "2023-11-19T13:06:16.190Z"
              },
              {
                "_id": "655a08473e09b17fe5eeed28",
                "imgUrl": "https://www.nytimes.com/images/2023/04/04/multimedia/00VIRTUAL-VETS-01b-fmzk/00VIRTUAL-VETS-01b-fmzk-blog480.jpg",
                "title": "The Virtual Vet Will See You Meow",
                "text": "Veterinary telemedicine could help more pet owners access much-needed care and put anxious animals at ease, but challenges remain.",
                "date": "2023-04-07T09:00:46.000Z",
                "url": "https://www.nytimes.com/2023/04/07/health/vet-pet-health-telemedicine.html",
                "nytID": "nyt://article/992f2f7f-793c-5553-b722-348625f53a4b",
                "createdAt": "2023-11-19T13:06:16.191Z",
                "updatedAt": "2023-11-19T13:06:16.191Z"
              }
            ],
            "total": 1151,
            "totalPages": 116
          }
        }
      }
    },

    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
